name: .NET Core CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore ./Bot/Lunaris2.csproj

    - name: Build
      run: dotnet build ./Bot/Lunaris2.csproj --no-restore
